import Head from "next/head";
import { Box } from "@chakra-ui/react";
import DataTable from "Base/components/DataTable";

interface ParcelRow {
  name: string;
  service: string;
}

export default function Home() {
  const columns = [
    {
      label: "Nombre",
      selector: (row: ParcelRow) => row.name,
    },
    {
      label: "Servicio",
      selector: (row: ParcelRow) => row.service,
    },
  ];
  return (
    <>
      <Head>
        <title>Home</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      {/* <Box as="main" p={4}>
        <DataTable columns={columns} data={[]} />
      </Box> */}
    </>
  );
}
